files: |
    (?x)^(
        electroncash_gui/qt/address_list.py
    )$
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        name: isort (python)
    -   id: isort
        name: isort (cython)
        types: [cython]
    -   id: isort
        name: isort (pyi)
        types: [pyi]
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black

