exclude: 'pb2.py'
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black]
    -   id: isort
        name: isort (cython)
        types: [cython]
        args: [--profile=black]
    -   id: isort
        name: isort (pyi)
        types: [pyi]
        args: [--profile=black]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args:
        -   --preview
        exclude: icons.py
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    # Syntax errors checked on all files
    -   id: flake8
        args:
        -   --max-line-length=88
        -   --select=E1,E2,E3,E4,E5,E7,E9,F4,F5,F6,F7,F8,W1,W2,W3,W504,W6
        -   --ignore=E501   # FIXME
        -   --extend-ignore=E203   # This one is incompatible with black
        additional_dependencies:
        -   flake8-mutable
    # Less severe errors and warnings checked on a selection of cleaned-up files
    -   id: flake8
        args:
        -   --max-line-length=88
        -   --ignore=E203,E501,W503,SIM106,SIM119,FS002,FS003
        additional_dependencies:
        -   flake8-comprehensions
        -   flake8-mutable
        -   flake8-simplify
        -   flake8-use-fstring
        files: |
          (?x)^(
              electrumabc/tests/.*py|
              electrumabc/avalanche/.*py|
              electrumabc/consolidate.py|
              electrumabc/constants.py|
              electrumabc/invoice.py|
              electrumabc/keystore.py|
              electrumabc/monotonic.py|
              electrumabc/printerror.py|
              electrumabc/uint256.py|
              electrumabc/web.py|
              electrumabc_gui/qt/address_list.py|
              electrumabc_gui/qt/amountedit.py|
              electrumabc_gui/qt/avalanche/.*py|
              electrumabc_gui/qt/consolidate_coins_dialog.py|
              electrumabc_gui/qt/exception_window.py|
              electrumabc_gui/qt/invoice_dialog.py|
              electrumabc_gui/qt/multi_transactions_dialog.py|
              electrumabc_gui/qt/sign_verify_dialog.py|
              electrumabc_gui/qt/statusbar.py|
              electrumabc_gui/qt/utxo_list.py|
              electrumabc_plugins/fusion/cmdline.py
          )$
